all: kalmanFilterEqsDerivation.pdf

kalmanFilterEqsDerivation.pdf: kalmanFilterEqsDerivation.tex
	pdflatex kalmanFilterEqsDerivation.tex
	bibtex kalmanFilterEqsDerivation.aux
	pdflatex kalmanFilterEqsDerivation.tex
	pdflatex kalmanFilterEqsDerivation.tex


